// Generated by gencpp from file object_msgs/AddMovingObjectsResponse.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_ADDMOVINGOBJECTSRESPONSE_H
#define OBJECT_MSGS_MESSAGE_ADDMOVINGOBJECTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_msgs
{
template <class ContainerAllocator>
struct AddMovingObjectsResponse_
{
  typedef AddMovingObjectsResponse_<ContainerAllocator> Type;

  AddMovingObjectsResponse_()
    {
    }
  AddMovingObjectsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddMovingObjectsResponse_

typedef ::object_msgs::AddMovingObjectsResponse_<std::allocator<void> > AddMovingObjectsResponse;

typedef boost::shared_ptr< ::object_msgs::AddMovingObjectsResponse > AddMovingObjectsResponsePtr;
typedef boost::shared_ptr< ::object_msgs::AddMovingObjectsResponse const> AddMovingObjectsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace object_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/AddMovingObjectsResponse";
  }

  static const char* value(const ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddMovingObjectsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::object_msgs::AddMovingObjectsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_ADDMOVINGOBJECTSRESPONSE_H
