// Generated by gencpp from file object_msgs/AddMovingObjects.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_ADDMOVINGOBJECTS_H
#define OBJECT_MSGS_MESSAGE_ADDMOVINGOBJECTS_H

#include <ros/service_traits.h>


#include <object_msgs/AddMovingObjectsRequest.h>
#include <object_msgs/AddMovingObjectsResponse.h>


namespace object_msgs
{

struct AddMovingObjects
{

typedef AddMovingObjectsRequest Request;
typedef AddMovingObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddMovingObjects
} // namespace object_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_msgs::AddMovingObjects > {
  static const char* value()
  {
    return "54b3c80efd6fae6e6ffff8a4b9facd69";
  }

  static const char* value(const ::object_msgs::AddMovingObjects&) { return value(); }
};

template<>
struct DataType< ::object_msgs::AddMovingObjects > {
  static const char* value()
  {
    return "object_msgs/AddMovingObjects";
  }

  static const char* value(const ::object_msgs::AddMovingObjects&) { return value(); }
};


// service_traits::MD5Sum< ::object_msgs::AddMovingObjectsRequest> should match
// service_traits::MD5Sum< ::object_msgs::AddMovingObjects >
template<>
struct MD5Sum< ::object_msgs::AddMovingObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_msgs::AddMovingObjects >::value();
  }
  static const char* value(const ::object_msgs::AddMovingObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_msgs::AddMovingObjectsRequest> should match
// service_traits::DataType< ::object_msgs::AddMovingObjects >
template<>
struct DataType< ::object_msgs::AddMovingObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::object_msgs::AddMovingObjects >::value();
  }
  static const char* value(const ::object_msgs::AddMovingObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_msgs::AddMovingObjectsResponse> should match
// service_traits::MD5Sum< ::object_msgs::AddMovingObjects >
template<>
struct MD5Sum< ::object_msgs::AddMovingObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_msgs::AddMovingObjects >::value();
  }
  static const char* value(const ::object_msgs::AddMovingObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_msgs::AddMovingObjectsResponse> should match
// service_traits::DataType< ::object_msgs::AddMovingObjects >
template<>
struct DataType< ::object_msgs::AddMovingObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::object_msgs::AddMovingObjects >::value();
  }
  static const char* value(const ::object_msgs::AddMovingObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_ADDMOVINGOBJECTS_H
