// Generated by gencpp from file control_core_msgs/JointState.msg
// DO NOT EDIT!


#ifndef CONTROL_CORE_MSGS_MESSAGE_JOINTSTATE_H
#define CONTROL_CORE_MSGS_MESSAGE_JOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <control_core_msgs/Vector.h>
#include <control_core_msgs/Vector.h>
#include <control_core_msgs/Vector.h>
#include <control_core_msgs/Vector.h>

namespace control_core_msgs
{
template <class ContainerAllocator>
struct JointState_
{
  typedef JointState_<ContainerAllocator> Type;

  JointState_()
    : position()
    , velocity()
    , acceleration()
    , effort()  {
    }
  JointState_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , velocity(_alloc)
    , acceleration(_alloc)
    , effort(_alloc)  {
  (void)_alloc;
    }



   typedef  ::control_core_msgs::Vector_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::control_core_msgs::Vector_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::control_core_msgs::Vector_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef  ::control_core_msgs::Vector_<ContainerAllocator>  _effort_type;
  _effort_type effort;





  typedef boost::shared_ptr< ::control_core_msgs::JointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_core_msgs::JointState_<ContainerAllocator> const> ConstPtr;

}; // struct JointState_

typedef ::control_core_msgs::JointState_<std::allocator<void> > JointState;

typedef boost::shared_ptr< ::control_core_msgs::JointState > JointStatePtr;
typedef boost::shared_ptr< ::control_core_msgs::JointState const> JointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_core_msgs::JointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_core_msgs::JointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_core_msgs::JointState_<ContainerAllocator1> & lhs, const ::control_core_msgs::JointState_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration &&
    lhs.effort == rhs.effort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_core_msgs::JointState_<ContainerAllocator1> & lhs, const ::control_core_msgs::JointState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::JointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::JointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::JointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::JointState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::JointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::JointState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_core_msgs::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4687c57ff41aed07b9255a1a224fc795";
  }

  static const char* value(const ::control_core_msgs::JointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4687c57ff41aed07ULL;
  static const uint64_t static_value2 = 0xb9255a1a224fc795ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_core_msgs::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_core_msgs/JointState";
  }

  static const char* value(const ::control_core_msgs::JointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_core_msgs::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Vector position\n"
"Vector velocity\n"
"Vector acceleration\n"
"Vector effort\n"
"================================================================================\n"
"MSG: control_core_msgs/Vector\n"
"float64[] data\n"
;
  }

  static const char* value(const ::control_core_msgs::JointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_core_msgs::JointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_core_msgs::JointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_core_msgs::JointState_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::control_core_msgs::Vector_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::control_core_msgs::Vector_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::control_core_msgs::Vector_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "effort: ";
    s << std::endl;
    Printer< ::control_core_msgs::Vector_<ContainerAllocator> >::stream(s, indent + "  ", v.effort);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_CORE_MSGS_MESSAGE_JOINTSTATE_H
