// Generated by gencpp from file control_core_msgs/LinearStateTrajectory.msg
// DO NOT EDIT!


#ifndef CONTROL_CORE_MSGS_MESSAGE_LINEARSTATETRAJECTORY_H
#define CONTROL_CORE_MSGS_MESSAGE_LINEARSTATETRAJECTORY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <control_core_msgs/LinearState.h>

namespace control_core_msgs
{
template <class ContainerAllocator>
struct LinearStateTrajectory_
{
  typedef LinearStateTrajectory_<ContainerAllocator> Type;

  LinearStateTrajectory_()
    : header()
    , time()
    , trajectory()  {
    }
  LinearStateTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time(_alloc)
    , trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _time_type;
  _time_type time;

   typedef std::vector< ::control_core_msgs::LinearState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::control_core_msgs::LinearState_<ContainerAllocator> >::other >  _trajectory_type;
  _trajectory_type trajectory;





  typedef boost::shared_ptr< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct LinearStateTrajectory_

typedef ::control_core_msgs::LinearStateTrajectory_<std::allocator<void> > LinearStateTrajectory;

typedef boost::shared_ptr< ::control_core_msgs::LinearStateTrajectory > LinearStateTrajectoryPtr;
typedef boost::shared_ptr< ::control_core_msgs::LinearStateTrajectory const> LinearStateTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator1> & lhs, const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time == rhs.time &&
    lhs.trajectory == rhs.trajectory;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator1> & lhs, const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a31d9d4fed89d56cfc1540ec77d1550c";
  }

  static const char* value(const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa31d9d4fed89d56cULL;
  static const uint64_t static_value2 = 0xfc1540ec77d1550cULL;
};

template<class ContainerAllocator>
struct DataType< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_core_msgs/LinearStateTrajectory";
  }

  static const char* value(const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64[] time\n"
"LinearState[] trajectory\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: control_core_msgs/LinearState\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration\n"
"geometry_msgs/Vector3 force\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinearStateTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_core_msgs::LinearStateTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time[]" << std::endl;
    for (size_t i = 0; i < v.time.size(); ++i)
    {
      s << indent << "  time[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.time[i]);
    }
    s << indent << "trajectory[]" << std::endl;
    for (size_t i = 0; i < v.trajectory.size(); ++i)
    {
      s << indent << "  trajectory[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::control_core_msgs::LinearState_<ContainerAllocator> >::stream(s, indent + "    ", v.trajectory[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_CORE_MSGS_MESSAGE_LINEARSTATETRAJECTORY_H
