// Generated by gencpp from file control_core_msgs/VectorStamped.msg
// DO NOT EDIT!


#ifndef CONTROL_CORE_MSGS_MESSAGE_VECTORSTAMPED_H
#define CONTROL_CORE_MSGS_MESSAGE_VECTORSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <control_core_msgs/Vector.h>

namespace control_core_msgs
{
template <class ContainerAllocator>
struct VectorStamped_
{
  typedef VectorStamped_<ContainerAllocator> Type;

  VectorStamped_()
    : header()
    , vector()  {
    }
  VectorStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vector(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::control_core_msgs::Vector_<ContainerAllocator>  _vector_type;
  _vector_type vector;





  typedef boost::shared_ptr< ::control_core_msgs::VectorStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_core_msgs::VectorStamped_<ContainerAllocator> const> ConstPtr;

}; // struct VectorStamped_

typedef ::control_core_msgs::VectorStamped_<std::allocator<void> > VectorStamped;

typedef boost::shared_ptr< ::control_core_msgs::VectorStamped > VectorStampedPtr;
typedef boost::shared_ptr< ::control_core_msgs::VectorStamped const> VectorStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_core_msgs::VectorStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_core_msgs::VectorStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_core_msgs::VectorStamped_<ContainerAllocator1> & lhs, const ::control_core_msgs::VectorStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vector == rhs.vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_core_msgs::VectorStamped_<ContainerAllocator1> & lhs, const ::control_core_msgs::VectorStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::VectorStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::VectorStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::VectorStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::VectorStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::VectorStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::VectorStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_core_msgs::VectorStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1af1b6b69f442d4a5deaeb506bbdee39";
  }

  static const char* value(const ::control_core_msgs::VectorStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1af1b6b69f442d4aULL;
  static const uint64_t static_value2 = 0x5deaeb506bbdee39ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_core_msgs::VectorStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_core_msgs/VectorStamped";
  }

  static const char* value(const ::control_core_msgs::VectorStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_core_msgs::VectorStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Vector vector\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: control_core_msgs/Vector\n"
"float64[] data\n"
;
  }

  static const char* value(const ::control_core_msgs::VectorStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_core_msgs::VectorStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VectorStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_core_msgs::VectorStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_core_msgs::VectorStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vector: ";
    s << std::endl;
    Printer< ::control_core_msgs::Vector_<ContainerAllocator> >::stream(s, indent + "  ", v.vector);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_CORE_MSGS_MESSAGE_VECTORSTAMPED_H
